# These are supported funding model platforms

patreon: https://www.patreon.com/EnigmaSoft?fan_landing=true
open_collective: wizdwarfs
ko_fi:  enigma0493
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
issuehunt:  https://issuehunt.io/u/ali2210
otechie:  https://otechie.com/wisdom-010
custom: buymeacoffee.com/ali2210
