name: ci


on:
  push:
    - 'master'


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
        
      name: Login Docker Credentials
      uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

     name: Push Artificat
     uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:mysubdir"
          push: true
          tags: user/app:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.MYTOKEN }}
